name: Build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        php: [ "8.2"]
        composer: [ "2.2.7" ]
    runs-on: ubuntu-latest
    container: php:${{ matrix.php }}-cli
    steps:
      - uses: actions/checkout@v2

      - name: Cache composer bin
        id: cache-composer-bin
        uses: actions/cache@v2
        with:
          path: ~/.local/bin/composer.phar
          key: ${{ runner.os }}-${{ matrix.composer }}-composer-bin

      - name: Generate composer bin
        if: steps.cache-composer-bin.outputs.cache-hit != 'true'
        run: mkdir -p ~/.local/bin/ && curl https://getcomposer.org/download/${{ matrix.composer }}/composer.phar -o ~/.local/bin/composer.phar -LR -z ~/.local/bin/composer.phar

      - name: Move composer bin
        run: cp ~/.local/bin/composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install ubuntu dependencies
        run: apt-get update --allow-releaseinfo-change && apt-get install -y libzip-dev unzip git

      - name: Install composer dependencies
        run: composer install

      - name: Run checks
        run: php vendor/bin/phpunit

      - name: Run checks in lower versions
        run: |
          composer update --prefer-lowest --prefer-dist --prefer-stable --no-interaction
          php vendor/bin/phpunit
